# Generated by Django 3.2 on 2021-05-06 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_contact', models.CharField(max_length=100)),
                ('hospital_city', models.CharField(max_length=100)),
                ('hospital_address', models.CharField(max_length=500)),
                ('hospital_beds', models.CharField(max_length=100)),
                ('hospital_verify', models.CharField(max_length=100)),
                ('hospital_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('dis_type', models.CharField(choices=[('Helping', 'Helping'), ('Help Needed', 'Help Needed')], max_length=100)),
                ('blood_grp', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_nos', models.CharField(blank=True, max_length=100, null=True)),
                ('map_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('information', models.TextField()),
                ('hashtags', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_supplier_name', models.CharField(max_length=100)),
                ('food_supplier_email', models.CharField(max_length=100)),
                ('food_supplier_contact', models.CharField(max_length=100)),
                ('food_supplier_city', models.CharField(max_length=100)),
                ('food_supplier_service', models.CharField(max_length=100)),
                ('food_supplier_verify', models.CharField(max_length=100)),
                ('food_supplier_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_lead_name', models.CharField(max_length=100)),
                ('injection_lead_email', models.CharField(max_length=100)),
                ('injection_lead_contact', models.CharField(max_length=100)),
                ('injection_lead_city', models.CharField(max_length=100)),
                ('injection_lead_drugname', models.CharField(max_length=100)),
                ('injection_lead_verify', models.CharField(max_length=100)),
                ('injection_lead_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_lead_name', models.CharField(max_length=100)),
                ('oxygen_lead_email', models.CharField(max_length=100)),
                ('oxygen_lead_contact', models.CharField(max_length=100)),
                ('oxygen_lead_city', models.CharField(max_length=100)),
                ('oxygen_lead_verify', models.CharField(max_length=100)),
                ('oxygen_lead_details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasma_donor_name', models.CharField(max_length=100)),
                ('plasma_donor_email', models.CharField(max_length=100)),
                ('plasma_donor_contact', models.CharField(max_length=100)),
                ('plasma_donor_city', models.CharField(max_length=100)),
                ('plasma_donor_bloodgroup', models.CharField(max_length=100)),
                ('plasma_donor_age', models.IntegerField()),
                ('plasma_donor_gender', models.CharField(max_length=100)),
                ('plasma_donor_confirm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srotApp.discussion')),
            ],
        ),
    ]
