# Generated by Django 3.1.7 on 2021-05-09 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_supplier_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
