# Generated by Django 3.1.7 on 2021-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasma_donor_name', models.CharField(max_length=100)),
                ('plasma_donor_email', models.CharField(max_length=100)),
                ('plasma_donor_contact', models.CharField(max_length=100)),
                ('plasma_donor_bloodgroup', models.CharField(max_length=100)),
                ('plasma_donor_age', models.IntegerField()),
                ('plasma_donor_gender', models.CharField(max_length=100)),
                ('plasma_donor_confirm', models.CharField(max_length=100)),
            ],
        ),
    ]
