# Generated by Django 3.1.7 on 2021-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beds',
            name='volunteer_verify',
            field=models.CharField(default='Unverified', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='volunteer_verify',
            field=models.CharField(default='Unverified', max_length=100),
        ),
        migrations.AddField(
            model_name='injection',
            name='volunteer_verify',
            field=models.CharField(default='Unverified', max_length=100),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='volunteer_verify',
            field=models.CharField(default='Unverified', max_length=100),
        ),
        migrations.AddField(
            model_name='plasma',
            name='volunteer_verify',
            field=models.CharField(default='Unverified', max_length=100),
        ),
    ]
