# Generated by Django 3.1.7 on 2021-05-04 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0002_plasma'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasma',
            name='plasma_donor_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
