# Generated by Django 3.1.7 on 2021-05-09 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0002_food_food_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='injection_lead_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
