# Generated by Django 3.1.7 on 2021-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0003_plasma_plasma_donor_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_lead_name', models.CharField(max_length=100)),
                ('oxygen_lead_email', models.CharField(max_length=100)),
                ('oxygen_lead_contact', models.CharField(max_length=100)),
                ('oxygen_lead_city', models.CharField(max_length=100)),
                ('oxygen_lead_verify', models.CharField(max_length=100)),
            ],
        ),
    ]
