# Generated by Django 3.1.7 on 2021-05-05 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0004_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='oxygen_lead_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
