# Generated by Django 3.1.7 on 2021-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0005_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_aadhar',
            field=models.FileField(upload_to='vol_aadhar'),
        ),
    ]
