# Generated by Django 3.1.7 on 2021-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0005_oxygen_oxygen_lead_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injection_lead_name', models.CharField(max_length=100)),
                ('injection_lead_email', models.CharField(max_length=100)),
                ('injection_lead_contact', models.CharField(max_length=100)),
                ('injection_lead_city', models.CharField(max_length=100)),
                ('injection_lead_drugname', models.CharField(max_length=100)),
                ('injection_lead_verify', models.CharField(max_length=100)),
                ('injection_lead_details', models.CharField(max_length=500)),
            ],
        ),
    ]
