# Generated by Django 3.1.7 on 2021-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0006_injection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_supplier_name', models.CharField(max_length=100)),
                ('food_supplier_email', models.CharField(max_length=100)),
                ('food_supplier_contact', models.CharField(max_length=100)),
                ('food_supplier_city', models.CharField(max_length=100)),
                ('food_supplier_service', models.CharField(max_length=100)),
                ('food_supplier_verify', models.CharField(max_length=100)),
                ('food_supplier_details', models.CharField(max_length=500)),
            ],
        ),
    ]
