# Generated by Django 3.2.3 on 2021-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0002_volunteer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beds',
            name='volunteer_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='food',
            name='volunteer_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='injection',
            name='volunteer_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='oxygen',
            name='volunteer_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='plasma',
            name='volunteer_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
