# Generated by Django 3.2.3 on 2021-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srotApp', '0003_auto_20210521_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_supplier_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='injection',
            name='injection_lead_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='oxygen_lead_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='plasma_donor_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
