from django.urls import path
from . import views

urlpatterns = [
    
    path('discussions/',views.discussions,name="discussions"),
    path('showComments/',views.showComments,name="showDComments"),
    path('saveDComment/',views.saveDiscussionComment,name="save_d_comment"),
    path('donations/sidebar/',views.sidebar,name="sidebar"),
    path('donations/plasma/',views.plasma,name="plasma"),
    path('donations/oxygen/',views.oxygen,name="oxygen"),
    path('donations/injections/',views.injections,name="injections"),
    path('donations/food/',views.food,name="food"),
    path('donations/beds/',views.beds,name="beds"),
    path('leads/foodleads',views.foodleads,name="foodleads"),
    path('leads/bedleads',views.bedleads,name="bedleads"),
    path('leads/injectionleads',views.injectionleads,name="injectionleads"),
    path('leads/oxygenleads',views.oxygenleads,name="oxygenleads"),
    path('leads/plasmaleads',views.plasmaleads,name="plasmaleads"),
    path('leads/filter',views.filter,name="filter"),
    path('',views.home,name="home"),
    path('volunteer/landing',views.landing,name="landing"),
    path('volunteer/food',views.volfood,name="volfood"),
    path('editfood/',views.editfood,name="editfood"),
    path('volunteer/beds',views.volbeds,name="volbeds"),
    path('edithospital/',views.edithospital,name="edithospital"),
    path('volunteer/injections',views.volinjection,name="volinjection"),
    path('volunteer/oxygen',views.voloxygen,name="voloxygen"),
    path('volunteer/plasma',views.volplasma,name="volplasma"),
    path('deleteLead/<str:resource>/<int:id>',views.deleteLead,name="deleteLead"),
    path('verifyLead/<str:resource>/<int:id>',views.verifyLead,name="verifyLead"),
    path('editoxygen/',views.editoxygen,name="editoxygen"),
    path('editinjection/',views.editinjection,name="editinjection"),
    path('editplasma/',views.editplasma,name="editplasma"),
    path('volForm/',views.volForm,name="volForm"),
]
